sonar.host.url=https://sonarcloud.io
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sources=.
sonar.exclusions=node_modules/**,test/**,tests/**,coverage/**,evidence/**,.scanner-cli/**,.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
